---
mmdebstrap:
  architectures:
    - arm64
  keyrings:
    - /usr/share/keyrings/debian-archive-keyring.gpg
  mode: auto
  packages:
    - init
    - libpam-systemd
    - iproute2
    - less
    - locales
    - openssh-server
    - sudo
    - neofetch
    - vim
  suite: unstable
  variant: standard
  essential-hooks:
    # FIXME: Find a better workaround instead of sleep
    - 'sleep 10' # workaround for /proc resource busy unable to umount issue
  customize-hooks:
    - 'chroot "$1" passwd --delete root'
    - 'chroot "$1" chown -R man: /var/cache/man/'
    - 'chroot "$1" chown -R man: /var/cache/man/'
    - 'chroot "$1" apt update'
    - 'chroot "$1" cp /etc/skel/.bashrc ~/.bashrc'

