# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" and "dev" branches
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install Dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update; sudo apt-get upgrade
          sudo apt-get install -y binfmtc binfmt-support pv pigz \
              qemu-user qemu-user-static qemu-system-arm \
              debian-archive-keyring bdebstrap
          sudo apt-get install build-essential autoconf automake bison flex libssl-dev bc u-boot-tools swig

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          mkdir -p build
          sudo ./build.sh

      # Upload
      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          path: build/*am62xx-evm*.tar.xz
          name: am62xx-evm-artifacts
          if-no-files-found: error

      # Upload
      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          path: build/bsp_sources.tar.xz
          name: bsp_sources_common
          if-no-files-found: error

